controllers:
  resource: ../../src/Controller/
  type: annotation
  prefix:
    bg: ''
    en: '/en'
  # requirements:
  #     _locale: 'bg|en'

kernel:
  resource: ../../src/Kernel.php
  type: annotation
